In [56]:
import pandas as pd
import numpy as np

In [57]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)


## How to convert the index of a series into a column of a dataframe?

In [58]:
df = ser.to_frame().reset_index()
print(df.head())

  index  0
0     a  0
1     b  1
2     c  2
3     e  3
4     d  4


## How to combine many series to form a dataframe?

In [59]:
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

In [60]:
df = pd.concat([ser1, ser2], axis=1)
print(df.head())

   0  1
0  a  0
1  b  1
2  c  2
3  e  3
4  d  4


## How to assign name to the series’ index?

In [61]:
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser.name = 'alphabets'
ser.head()

0    a
1    b
2    c
3    e
4    d
Name: alphabets, dtype: object

## How to get the items of series A not present in series B?

In [62]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
ser1.name = 'ser1'
# isin() valida se o valor está presente na série, e o ~ inverte o resultado
ser1[~ser1.isin(ser2)]

0    1
1    2
2    3
Name: ser1, dtype: int64

## How to get the items not common to both series A and series B?

In [63]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

In [64]:
ser_u = pd.Series(np.union1d(ser1, ser2))  # union / unique no repeat
ser_i = pd.Series(np.intersect1d(ser1, ser2))  # intersect / common
print(ser_i)

0    4
1    5
dtype: int64


In [65]:
ser_u[~ser_u.isin(ser_i)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [66]:
~ser_u.isin(ser_i)

0     True
1     True
2     True
3    False
4    False
5     True
6     True
7     True
dtype: bool

In [67]:
ser_u.isin(ser_i)

0    False
1    False
2    False
3     True
4     True
5    False
6    False
7    False
dtype: bool

## How to get the minimum, 25th percentile, median, 75th, and max of a numeric series?

In [68]:
ser = pd.Series(np.random.normal(10, 5, 25))

In [69]:
print(ser)

0     11.046136
1      7.171250
2     12.443970
3     12.704918
4     12.671256
5     12.501918
6     12.665093
7     13.488604
8      6.600297
9      9.181183
10    17.137073
11     4.196023
12    16.789508
13    12.272034
14     8.675545
15     4.349482
16     6.730703
17     5.031889
18     1.224762
19     4.034081
20     4.693723
21    10.947614
22    14.989886
23     6.607571
24     8.619989
dtype: float64


In [70]:
np.percentile(ser, q=[0, 25, 50, 75, 100])

array([ 1.22476186,  6.60029732,  9.18118264, 12.66509342, 17.1370729 ])

In [71]:
ser.describe()

count    25.000000
mean      9.470980
std       4.306903
min       1.224762
25%       6.600297
50%       9.181183
75%      12.665093
max      17.137073
dtype: float64

## How to get frequency counts of unique items of a series?

In [72]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

In [73]:
ser.value_counts()

b    7
e    6
g    6
c    5
f    2
h    2
a    1
d    1
Name: count, dtype: int64

# How to keep only top 2 most frequent values as it is and replace everything else as Other?

In [74]:
np.random.RandomState(100)
#cria uma Series chamada ser que contém 12 números inteiros aleatórios entre 1 e 4.
ser = pd.Series(np.random.randint(1, 5, [12]))

In [75]:
# ser.value_counts().index[:2] retorna os dois índices com as maiores contagens.
# ~ser.isin(ser.value_counts().index[:2]) retorna uma Series booleana que é True para os valores em ser que não estão nos dois índices com as maiores contagens
# ser[~ser.isin(ser.value_counts().index[:2])] = 'Other' substitui todos os valores em ser que não estão nos dois índices com as maiores contagens por 'Other'.

In [76]:
print("Top 2 freq:", ser.value_counts())
ser[~ser.isin(ser.value_counts().index[:2])] = 'Other'
ser

Top 2 freq: 1    5
2    3
3    2
4    2
Name: count, dtype: int64


/tmp/ipykernel_54135/1646089746.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Other' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ser[~ser.isin(ser.value_counts().index[:2])] = 'Other'


0     Other
1         2
2         2
3         1
4         1
5     Other
6         1
7         1
8         1
9     Other
10        2
11    Other
dtype: object

# How to bin a numeric series to 10 groups of equal size?

In [77]:
ser = pd.Series(np.random.random(20))
print(ser.head())

0    0.678638
1    0.890025
2    0.087384
3    0.612228
4    0.986618
dtype: float64


In [78]:
pd.qcut(ser, q=[0, .10, .20, .3, .4, .5, .6, .7, .8, .9, 1], labels=['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th'])

0      6th
1      8th
2      1st
3      5th
4     10th
5      3rd
6      9th
7      2nd
8     10th
9      4th
10     7th
11     2nd
12     1st
13     6th
14     9th
15     4th
16     5th
17     8th
18     7th
19     3rd
dtype: category
Categories (10, object): ['1st' < '2nd' < '3rd' < '4th' ... '7th' < '8th' < '9th' < '10th']

# How to convert a numpy array to a dataframe of given shape?

In [79]:
ser = pd.Series(np.random.randint(1, 10, 35))
print(ser.head())

0    4
1    2
2    3
3    1
4    7
dtype: int64


In [80]:
teste = ser.values.reshape(7, 5)
print(teste)

[[4 2 3 1 7]
 [6 7 6 4 8]
 [1 8 1 2 1]
 [2 9 5 1 2]
 [4 5 2 9 2]
 [1 3 8 5 5]
 [1 2 1 4 2]]


In [81]:
print(teste[1])

[6 7 6 4 8]


In [82]:
df = pd.DataFrame(ser.values.reshape(7, 5))

In [83]:
df

0  1  2  3  4
0  4  2  3  1  7
1  6  7  6  4  8
2  1  8  1  2  1
3  2  9  5  1  2
4  4  5  2  9  2
5  1  3  8  5  5
6  1  2  1  4  2

# How to find the positions of numbers that are multiples of 3 from a series?

In [84]:
# cria uma Series chamada ser com 7 valores aleatórios entre 1 e 10.
ser = pd.Series(np.random.randint(1, 10, 7))
ser.head(7)

0    9
1    7
2    7
3    7
4    7
5    3
6    1
dtype: int64

In [85]:
np.argwhere(ser % 3==0) #retorna os índices dos valores em ser que são múltiplos de 3.

array([[0],
       [5]])

# How to extract items at given positions from a series

In [86]:
# # ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
# # ser = pd.Series(np.array(list('abcdefghijklmnopqrstuvwxyz')))
# ser = pd.Series(np.array(list('abcdefghijklmnopqrstuvwxyz')))
# pos = [0, 4, 8, 14, 20]
# # pos

In [87]:
# ser = pd.Series(np.array(list('abcdefghijklmnopqrstuvwxyz')))
# pos = np.array(pos)
# 
# print(ser[pos])


# How to stack two series vertically and horizontally ?

In [88]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(['a', 'b', 'c', 'd', 'e'])

In [89]:
pd.concat([ser1, ser2], axis=1)

0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e

# How to get the positions of items of series A in another series B?

In [90]:
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

In [91]:
[np.where(i == ser1)[0].tolist()[0] for i in ser2]

[5, 4, 0, 8]

In [92]:
[pd.Index(ser1).get_loc(i) for i in ser2]

[5, 4, 0, 8]

In [93]:
for i in ser2:
    print(i)

1
3
10
13


In [94]:
pd.Index(ser1).get_loc(9)

1

# How to compute the mean squared error on a truth and predicted series?

In [95]:
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10) # cria uma Series com 10 valores, começando em 0 e terminando em 9. A cada valor é adicionado um valor aleatório entre 0 e 1.

In [96]:
np.mean((truth-pred)**2)

0.29411741052006657

In [97]:
truth - pred

0   -0.182848
1   -0.717131
2   -0.044160
3   -0.139247
4   -0.843879
5   -0.571570
6   -0.470785
7   -0.481565
8   -0.738437
9   -0.578332
dtype: float64

In [98]:
(truth - pred)**2

0    0.033433
1    0.514277
2    0.001950
3    0.019390
4    0.712132
5    0.326692
6    0.221638
7    0.231905
8    0.545289
9    0.334468
dtype: float64

# How to convert the first character of each element in a series to uppercase?

In [99]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

In [100]:
ser.map(lambda x: x.title())

0     How
1      To
2    Kick
3    Ass?
dtype: object

In [101]:
ser.map(lambda x: x[0].upper() + x[1:])

0     How
1      To
2    Kick
3    Ass?
dtype: object

In [102]:
pd.Series([i.title() for i in ser])

0     How
1      To
2    Kick
3    Ass?
dtype: object

# How to calculate the number of character in each word in a series

In [103]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

In [104]:
ser.map(lambda x: len(x))

0    3
1    2
2    4
3    4
dtype: int64

# How to compute difference of differences between consequtive numbers of a series?

In [105]:
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

In [106]:
print(ser.diff().tolist())

[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]


In [107]:
print(ser.diff().diff().tolist())

[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]


# How to convert a series of date-string to a timeseries?

In [108]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

In [109]:
pd.to_datetime(ser)

ValueError: time data "02-02-2011" doesn't match format "%d %b %Y", at position 1. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [ ]:
from dateutil.parser import parse
ser.map(lambda x: parse(x))

# How to get the day of month, week number, day of year and day of week from a series of date strings?

In [ ]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

In [ ]:
ser_ts = ser.map(lambda x: parse(x))
ser_ts

In [ ]:
print("Date: ", ser_ts.dt.day.tolist())
print("Week number: ", ser_ts.dt.isocalendar().week.tolist())
print("day number of year: ",ser_ts.dt.dayofyear.tolist())
print("Day of week: ", ser_ts.dt.day_name().tolist())

# How to convert year-month string to dates corresponding to the 4th day of the month?

In [ ]:
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])

In [ ]:
ser_ts = ser.map(lambda x: parse('04 ' + x))
ser_ts

# How to filter words that contain atleast 2 vowels from a series?

In [ ]:
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])

In [ ]:
from collections import Counter
mask = ser.map(lambda x: sum([Counter(x.lower()).get(i, 0) for i in list('aeiou')]) >= 2)
ser[mask]

# How to filter valid emails from a series?

In [ ]:
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern = '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'

In [ ]:
import re
emails.str.findall(pattern, flags=re.IGNORECASE)

In [ ]:
[x[0] for x in [x for x in emails.str.findall(pattern) if len(x) > 0]]

# How to get the mean of a series grouped by another series?

In [ ]:
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10)) # cria uma Series com 10 valores, começando em 1 e terminando em 10.
print(weights.tolist())
print(fruit.tolist())

In [ ]:
weights.groupby(fruit).mean()

# How to compute the euclidean distance between two series?

In [ ]:
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

In [ ]:
sum((p - q)**2)**.5

In [ ]:
np.linalg.norm(p-q)

In [ ]:
p-q

# How to find all the local maxima (or peaks) in a numeric series?

In [ ]:
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])

In [ ]:
dd = np.diff(np.sign(np.diff(ser)))
peak_locs = np.where(dd == -2)[0] + 1
peak_locs

In [ ]:
ser[peak_locs]

In [ ]:
np.diff(ser)

In [ ]:
np.sign(np.diff(ser))

In [ ]:
np.diff(np.sign(np.diff(ser)))

# How to replace missing spaces in a string with the least frequent character?

In [ ]:
my_str = 'dbc deb abed gade'

In [ ]:
ser = pd.Series(list('dbc deb abed gade'))
freq = ser.value_counts()
freq

In [ ]:
least_freq = freq.dropna().index[-1]
"".join(ser.replace(' ', least_freq))

In [ ]:
print(least_freq)

# How to create a TimeSeries starting ‘2000-01-01’ and 10 weekends (saturdays) after that having random numbers as values?

In [ ]:
ser = pd.Series(np.random.randint(1, 10, 10), pd.date_range('2000-01-01', periods=10, freq='W-SAT'))
ser

In [ ]:
np.random.randint(1, 10, 10) # cria uma Series com 10 valores aleatórios entre 1 e 10.
pd.date_range('2000-01-01', periods=10, freq='W-SAT') # cria uma Series com 10 datas, começando em 2000-01-01 e terminando em 2000-03-04, com frequência semanal aos sábados.

# How to fill an intermittent time series so all missing dates show up with values of previous non-missing date?

In [112]:
ser = pd.Series([1, 10, 3, np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
ser

2000-01-01     1.0
2000-01-03    10.0
2000-01-06     3.0
2000-01-08     NaN
dtype: float64

In [111]:
ser.resample('D').ffill() # resample('D') cria uma Series com frequência diária, e ffill() preenche os valores faltantes com o valor anterior.

2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     NaN
Freq: D, dtype: float64

In [113]:
ser.resample('D').bfill() # resample('D') cria uma Series com frequência diária, e bfill() preenche os valores faltantes com o valor posterior.

2000-01-01     1.0
2000-01-02    10.0
2000-01-03    10.0
2000-01-04     3.0
2000-01-05     3.0
2000-01-06     3.0
2000-01-07     NaN
2000-01-08     NaN
Freq: D, dtype: float64

In [114]:
ser.resample('D').bfill().ffill() # resample('D') cria uma Series com frequência diária, e bfill() preenche os valores faltantes com o valor posterior, e ffill() preenche os valores faltantes com o valor anterior.

2000-01-01     1.0
2000-01-02    10.0
2000-01-03    10.0
2000-01-04     3.0
2000-01-05     3.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     3.0
Freq: D, dtype: float64

# How to compute the autocorrelations of a numeric series?

In [117]:
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))
ser

0     -8.027988
1     -6.202589
2     -1.735865
3      1.344939
4      3.011417
5     20.350215
6     -4.376035
7      5.938298
8      8.330342
9     14.680695
10    -2.112779
11    14.547442
12    -7.993968
13    25.868252
14    -0.663148
15    -0.968974
16    28.969195
17    14.207964
18    14.327766
19     7.040235
dtype: float64

In [121]:
autocorrelations = [ser.autocorr(i).round(2) for i in range(11)]
print(autocorrelations[1:])
print('Lag having highest correlation: ', np.argmax(np.abs(autocorrelations[1:])) + 1)

[-0.17, 0.2, 0.08, 0.09, 0.03, 0.09, -0.15, 0.39, 0.1, -0.17]
Lag having highest correlation:  8


# How to import only every nth row from a csv file to create a dataframe?

In [140]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', chunksize=50)
df2 = pd.DataFrame()

In [141]:
df.get_chunk()

crim    zn  indus  chas    nox     rm    age     dis  rad  tax  \
0   0.00632  18.0   2.31     0  0.538  6.575   65.2  4.0900    1  296   
1   0.02731   0.0   7.07     0  0.469  6.421   78.9  4.9671    2  242   
2   0.02729   0.0   7.07     0  0.469  7.185   61.1  4.9671    2  242   
3   0.03237   0.0   2.18     0  0.458  6.998   45.8  6.0622    3  222   
4   0.06905   0.0   2.18     0  0.458  7.147   54.2  6.0622    3  222   
5   0.02985   0.0   2.18     0  0.458  6.430   58.7  6.0622    3  222   
6   0.08829  12.5   7.87     0  0.524  6.012   66.6  5.5605    5  311   
7   0.14455  12.5   7.87     0  0.524  6.172   96.1  5.9505    5  311   
8   0.21124  12.5   7.87     0  0.524  5.631  100.0  6.0821    5  311   
9   0.17004  12.5   7.87     0  0.524  6.004   85.9  6.5921    5  311   
10  0.22489  12.5   7.87     0  0.524  6.377   94.3  6.3467    5  311   
11  0.11747  12.5   7.87     0  0.524  6.009   82.9  6.2267    5  311   
12  0.09378  12.5   7.87     0  0.524  5.889   39.0  5.4509    5  311   
13  0.62976   0.0   8.14     0  0.538  5.949   61.8  4.7075    4  307   
14  0.63796   0.0   8.14     0  0.538  6.096   84.5  4.4619    4  307   
15  0.62739   0.0   8.14     0  0.538  5.834   56.5  4.4986    4  307   
16  1.05393   0.0   8.14     0  0.538  5.935   29.3  4.4986    4  307   
17  0.78420   0.0   8.14     0  0.538  5.990   81.7  4.2579    4  307   
18  0.80271   0.0   8.14     0  0.538  5.456   36.6  3.7965    4  307   
19  0.72580   0.0   8.14     0  0.538  5.727   69.5  3.7965    4  307   
20  1.25179   0.0   8.14     0  0.538  5.570   98.1  3.7979    4  307   
21  0.85204   0.0   8.14     0  0.538  5.965   89.2  4.0123    4  307   
22  1.23247   0.0   8.14     0  0.538  6.142   91.7  3.9769    4  307   
23  0.98843   0.0   8.14     0  0.538  5.813  100.0  4.0952    4  307   
24  0.75026   0.0   8.14     0  0.538  5.924   94.1  4.3996    4  307   
25  0.84054   0.0   8.14     0  0.538  5.599   85.7  4.4546    4  307   
26  0.67191   0.0   8.14     0  0.538  5.813   90.3  4.6820    4  307   
27  0.95577   0.0   8.14     0  0.538  6.047   88.8  4.4534    4  307   
28  0.77299   0.0   8.14     0  0.538  6.495   94.4  4.4547    4  307   
29  1.00245   0.0   8.14     0  0.538  6.674   87.3  4.2390    4  307   
30  1.13081   0.0   8.14     0  0.538  5.713   94.1  4.2330    4  307   
31  1.35472   0.0   8.14     0  0.538  6.072  100.0  4.1750    4  307   
32  1.38799   0.0   8.14     0  0.538  5.950   82.0  3.9900    4  307   
33  1.15172   0.0   8.14     0  0.538  5.701   95.0  3.7872    4  307   
34  1.61282   0.0   8.14     0  0.538  6.096   96.9  3.7598    4  307   
35  0.06417   0.0   5.96     0  0.499  5.933   68.2  3.3603    5  279   
36  0.09744   0.0   5.96     0  0.499  5.841   61.4  3.3779    5  279   
37  0.08014   0.0   5.96     0  0.499  5.850   41.5  3.9342    5  279   
38  0.17505   0.0   5.96     0  0.499  5.966   30.2  3.8473    5  279   
39  0.02763  75.0   2.95     0  0.428  6.595   21.8  5.4011    3  252   
40  0.03359  75.0   2.95     0  0.428  7.024   15.8  5.4011    3  252   
41  0.12744   0.0   6.91     0  0.448  6.770    2.9  5.7209    3  233   
42  0.14150   0.0   6.91     0  0.448  6.169    6.6  5.7209    3  233   
43  0.15936   0.0   6.91     0  0.448  6.211    6.5  5.7209    3  233   
44  0.12269   0.0   6.91     0  0.448  6.069   40.0  5.7209    3  233   
45  0.17142   0.0   6.91     0  0.448  5.682   33.8  5.1004    3  233   
46  0.18836   0.0   6.91     0  0.448  5.786   33.3  5.1004    3  233   
47  0.22927   0.0   6.91     0  0.448  6.030   85.5  5.6894    3  233   
48  0.25387   0.0   6.91     0  0.448  5.399   95.3  5.8700    3  233   
49  0.21977   0.0   6.91     0  0.448  5.602   62.0  6.0877    3  233   

    ptratio       b  lstat  medv  
0      15.3  396.90   4.98  24.0  
1      17.8  396.90   9.14  21.6  
2      17.8  392.83   4.03  34.7  
3      18.7  394.63   2.94  33.4  
4      18.7  396.90   5.33  36.2  
5      18.7  394.12   5.21  28.7  
6      15.2  395.60  12.43  22.9  
7  

In [145]:
for chunk in df:
    df2 = pd.concat([df2, chunk.iloc[0, :1]])

In [146]:
df2

crim    zn  indus  chas    nox     rm    age     dis  rad  tax  \
100   0.14866   0.0   8.56     0  0.520  6.727   79.9  2.7778    5  384   
150   1.65660   0.0  19.58     0  0.871  6.122   97.3  1.6180    5  403   
200   0.01778  95.0   1.47     0  0.403  7.135   13.9  7.6534    3  402   
250   0.14030  22.0   5.86     0  0.431  6.487   13.0  7.3967    7  330   
300   0.04417  70.0   2.24     0  0.400  6.871   47.4  7.8278    5  358   
350   0.06211  40.0   1.25     0  0.429  6.490   44.4  8.7921    1  335   
400  25.04610   0.0  18.10     0  0.693  5.987  100.0  1.5888   24  666   
450   6.71772   0.0  18.10     0  0.713  6.749   92.6  2.3236   24  666   
500   0.22438   0.0   9.69     0  0.585  6.027   79.7  2.4982    6  391   

     ptratio       b  lstat  medv  
100     20.9  394.76   9.42  27.5  
150     14.7  372.80  14.10  21.5  
200     17.0  384.30   4.45  32.9  
250     19.1  396.28   5.90  24.4  
300     14.8  390.86   6.07  24.8  
350     19.7  396.90   5.98  22.9  
400     20.2  396.90  26.77   5.6  
450     20.2    0.32  17.44  13.4  
500     19.2  396.90  14.33  16.8

# How to create a dataframe with rows as strides from a given series?

In [148]:
L = pd.Series(range(15))
L

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
dtype: int64

In [153]:
def gen_strides(a, stride_len=5, window_len=5):
    n_strides = ((a.size-window_len)//stride_len) + 1
    return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])

gen_strides(L, stride_len=2, window_len=4)

array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]])

 a
